use_frameworks!

platform :ios, '10.0'

target 'CategoryCollection_Example' do
  pod 'CategoryCollection', :path => '../'

  target 'CategoryCollection_Tests' do
    inherit! :search_paths

    
  end
end
